services:
  localstack:
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      SERVICES: ec2,lambda
      EC2_VM_MANAGER: docker
      EC2_DOCKER_FLAGS: --network fmi-net
      LAMBDA_DOCKER_NETWORK: fmi-net
      DOCKER_HOST: unix:///var/run/docker.sock
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fmi-net

  redis:
    image: redis:7
    container_name: fmi-redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - fmi-net

networks:
  fmi-net:
    name: fmi-net
    driver: bridge
